import { useEffect } from 'react';
import { io, Socket } from 'socket.io-client';
import { useAuthStore } from '@/lib/store/useAuthStore';
import { useRouter } from 'next/navigation';
import { auth } from '@/lib/firebase';

export const useRealtimeUpdates = () => {
    const { user } = useAuthStore();
    const router = useRouter();

    useEffect(() => {
        if (!user) return;

        let socket: Socket | undefined;

        const initSocket = async () => {
            await auth.authStateReady();
            const token = await auth.currentUser?.getIdToken();
            if (!token) return;

            // Initialize Socket connection
            socket = io(`${process.env.NEXT_PUBLIC_SOCKET_URL || 'http://localhost:8000'}/timetables`, {
                auth: { token }
            });

            socket.on('connect', () => {
                console.log('Real-time connection established.');
            });

            // Event for Department Admins when their master timetable is generated
            socket.on('timetable:generated', (data: any) => { // eslint-disable-line @typescript-eslint/no-explicit-any
                console.log('Timetable Generated Event Received:', data);
                window.dispatchEvent(new CustomEvent('timetable:generated', { detail: data }));
                alert(`New Timetable Matrix Generated! (Generation Time: ${data.generationMs}ms)${data.isSpecial ? ' [EMERGENCY SUBSTITUTION APPLIED]' : ''}`);
                router.refresh();
            });

            // Event for Faculty when their personal nested schedule updates
            socket.on('schedule:updated', (data: any) => { // eslint-disable-line @typescript-eslint/no-explicit-any
                console.log('Faculty Schedule Updated Event Received:', data);
                window.dispatchEvent(new CustomEvent('schedule:updated', { detail: data }));
                alert(`A new Master Schedule was generated by the department. Your Personal Timetable has been refreshed.`);
                router.refresh();
            });

            socket.on('connect_error', (err) => {
                console.error('Socket Connection Error:', err.message);
            });
        };

        initSocket();

        return () => {
            if (socket) socket.disconnect();
        };
    }, [user, router]);
};
